name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 22
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '22'
          java-package: 'jdk'
          check-latest: false
      
      - name: Check java version
        run: java --version
      
      - name: Build and Test with Maven
        run: mvn clean install -f demo-app/pom.xml
      
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:latest .
      
      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
      - name: Push Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:latest
      
      - name: Logout from Docker Hub
        if: always()
        run: docker logout